# Generated by Django 4.2.1 on 2023-05-22 17:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.PositiveSmallIntegerField(
                        default=255,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Picture width",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        default=255,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Picture height",
                    ),
                ),
                (
                    "paint_method",
                    models.CharField(
                        choices=[
                            ("sinusoidal", "Sinusoidal"),
                            ("sircular", "Circular"),
                            ("transition", "Transition"),
                        ],
                        default="transition",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "last_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("encryption", "Encryption"),
                            ("decryption", "Decryption"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Last action with this picture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Date of creating",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User pictures",
                    ),
                ),
            ],
        ),
    ]
