# Generated by Django 4.2.1 on 2023-05-22 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypt", "0002_picture_last_action_result_alter_picture_height_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="paint_method",
            new_name="draw_method",
        ),
    ]
