# Generated by Django 4.2.1 on 2023-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypt", "0003_rename_paint_method_picture_draw_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="If leave blank, will be generated randomly",
                max_length=20,
                null=True,
                verbose_name="Picture name",
            ),
        ),
    ]
