# Generated by Django 4.2.1 on 2023-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypt", "0004_picture_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="name",
        ),
        migrations.AlterField(
            model_name="picture",
            name="draw_method",
            field=models.CharField(
                choices=[
                    ("sinusoidal", "Sinusoidal"),
                    ("circular", "Circular"),
                    ("transition", "Transition"),
                ],
                default="transition",
                max_length=50,
            ),
        ),
    ]
