# Generated by Django 4.2.1 on 2023-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypt", "0005_remove_picture_name_alter_picture_draw_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="last_action_date",
            field=models.DateField(
                auto_now=True, db_index=True, verbose_name="Date of last action"
            ),
        ),
    ]
