# Generated by Django 4.2.1 on 2023-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypt", "0006_picture_last_action_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="picture",
            name="last_action_date",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Date of last action"
            ),
        ),
    ]
